---

- name: Install Rally dependencies
  apt: name="{{ item }}" state=present
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - libxml2-dev
    - libxslt1-dev
    - libpq-dev
    - git
    - python-pip
  sudo: yes

- name: Download Rally installation script
  get_url: url=https://raw.githubusercontent.com/openstack/rally/master/install_rally.sh dest=~

- name: Install Rally
  shell: 'bash ~/install_rally.sh -v -y --target {{rally_dir}}'

- shell: "chown {{global_os_user}}:{{global_os_user}} /home/{{global_os_user}}/rally -R"

- name: prepare rally
  shell: "{{ rally_dir }}/bin/rally deployment create --fromenv --name=existing"
  environment:
     OS_USERNAME: "{{ global_keystone_user }}"
     OS_PASSWORD: "{{ global_keystone_password }}"
     OS_AUTH_URL: "{{ global_keystone_auth }}"
     OS_ENDPOINT: "{{ global_keystone_auth }}"
     OS_TENANT_NAME: "{{ global_keystone_tenant }}"
