---

- name: Create Rally directory
  file: path={{ rally_dir }} owner={{ os_user }} mode=0644 state=directory

- name: Download Rally
  get_url: url=https://raw.githubusercontent.com/openstack/rally/master/install_rally.sh dest={{ rally_dir }}

- name: change owner and rights
  shell: "chown {{ os_user }}:{{ os_user }} {{ rally_dir }}/install_rally.sh; chmod 755 {{ rally_dir }}/install_rally.sh"
  sudo: yes

- name: Install Rally
  shell: "yes | {{ rally_dir }}/install_rally.sh --target {{ rally_dir }}"

- name: prepare rally
  shell: "{{ rally_dir }}/bin/rally deployment create --fromenv --name=existing"
  environment:
     #OS_USERNAME: "{{ keystone_user }}"
     #OS_PASSWORD: "{{ keystone_password }}"
     #OS_AUTH_URL: "{{ keystone_auth }}"
     #OS_TENANT_NAME: "{{ keystone_tenant }}"
     OS_USERNAME: admin
     OS_PASSWORD: tester
     OS_AUTH_URL: http://10.0.2.15:35357/v2.0
     OS_TENANT_NAME: admin
