- name: Configure Keystone database
  ini_file: >
    dest=/etc/keystone/keystone.conf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items:
    - section: database
      option: connection
      value: "{{ global_db }}://keystone:{{ global_keystone_password }}@localhost/keystone"

- name: Sync Keystone database
  command: '/bin/sh -c "{{ keystone_dir }}/venv/bin/keystone-manage db_sync" keystone'

#- include: run_keystone.yml
#  when: global_run_type == "eventlet"

- include: run_uwsgi.yml
  when: global_run_type == "uwsgi"

- include: run_apache.yml
  when: global_run_type == "apache"

- include: run_profile.yml
  when: global_run_type == "profile"

- pause: seconds=2

- include: endpoints.yml
- include: tenants.yml
- include: users.yml
- include: roles.yml
