- include: configuration.yml

- include: run_keystone.yml
  when: global_run_type == "eventlet"

- include: run_uwsgi.yml
  when: global_run_type == "uwsgi"

- include: run_apache.yml
  when: global_run_type == "apache"

- include: run_profile.yml
  when: global_run_type == "profile"

- pause: seconds=2

- include: endpoints.yml
- include: tenants.yml
- include: users.yml
- include: roles.yml
