- shell: "chmod 700 /var/log/keystone/admin.log"
  become: true
- shell: "chown {{ global_os_user }}:{{ global_os_user }} /var/log/keystone/admin.log"
  become: true
- name: Configure Keystone database
  ini_file: >
    dest=/etc/keystone/keystone.conf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items:
    - section: database
      option: connection
      value: "{{ global_db }}://keystone:{{ global_keystone_password }}@{{ hostvars[inventory_hostname]['groups']['bogomolov-cassandra-master'][0] }}/keystone"
  become: yes
- name: Sync Keystone database
  command: '/bin/sh -c "{{ keystone_dir }}/venv/bin/keystone-manage db_sync" keystone'
  ignore_errors: yes
  when: inventory_hostname == groups[cluster_name + '-slave-1'][0]

#- debug: msg="{{inventory_hostname}}, {{hostvars[inventory_hostname].openstack.private_v4}}"

- include: run_apache.yml

- pause: seconds=2

- name: Configure Keystone database
  ini_file: >
    dest=/etc/keystone/keystone.conf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items:
    - section: database
      option: connection
      value: "{{ global_db }}://keystone:{{ global_keystone_password }}@{{ hostvars[inventory_hostname]['groups']['bogomolov-cassandra-master'][0] }}/keystone"
  become: true


- name: Configure token
  ini_file: >
    dest=/etc/keystone/keystone.conf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items:
    - section: token
      option: provider
      value: "{{ global_token_provider }}"
  become: true
- name: Configure fernet tokens directory
  ini_file: >
    dest=/etc/keystone/keystone.conf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items:
    - section: fernet_tokens
      option: key_repository
      value: "/etc/keystone/fernet-keys/"
  when: global_token_provider == "fernet"
  become: yes
- name: Create fernet tokens
  shell: "{{ keystone_dir }}/venv/bin/keystone-manage fernet_setup"
  #ignore_errors: yes
  when: global_token_provider == "fernet"
  become: "modis"

- name: Sync Keystone database
  command: '/bin/sh -c "{{ keystone_dir }}/venv/bin/keystone-manage db_sync" keystone'
  ignore_errors: yes
  when: inventory_hostname == groups[cluster_name + '-slave-1'][0]


- include: run_apache.yml

- pause: seconds=2


- name: bootstrap fix
  shell: "{{ keystone_dir }}/venv/bin/keystone-manage bootstrap --bootstrap-username admin --bootstrap-password tester --bootstrap-service-name admin --bootstrap-admin-url http://{{ hostvars[inventory_hostname]['groups']['bogomolov_keystone_kong-HAProxy'] }}:35357/v3 --bootstrap-public-url http://{{ hostvars[inventory_hostname]['groups']['bogomolov_keystone_kong-HAProxy'] }}:5000/v3 --bootstrap-internal-url http://{{ hostvars[inventory_hostname]['groups']['bogomolov_keystone_kong-HAProxy'] }}:5000/v3 --bootstrap-project-name admin --bootstrap-role-name admin --bootstrap-region-id RegionOne"
  when: inventory_hostname == groups[cluster_name + '-slave-1'][0]
