---

- hosts: hosts
  roles:
    - role: ansible-mariadb
      mariadb_root_username: "{{ global_mariadb_user }}"
      mariadb_root_password: "{{ global_mariadb_password }}"
      mariad_default_config:
        - name: 'mysqld'
          config:
            - innodb_lof_file_size = 48M
      sudo: yes
#    - role: manage-db
    - role: openstack-keystone
      keystone_dir: /home/tester/keystone
      keystone_database_url: "mysql://keystone:{{ global_keystone_password }}@localhost/keystone"
      keystone_admin_token: "{{ global_keystone_token }}"
      keystone_tenants:
        - name: admin
          description: "Admin tenant"
        - name: service
          description: "Service tenant"
        - name: demo
          description: "Demo tenant"
      keystone_users:
        - name: "{{ global_keystone_user }}"
          password: "{{ global_keystone_password }}"
          tenant: admin
      keystone_roles:
        - name: admin
          user: admin
          tenant: admin
      keystone_services:
        - name: keystone
          service_type: identity
      keystone_endpoints:
        - service_name: keystone
          public_url: "http://10.0.2.15:5000"
          internal_url: "http://10.0.2.15:5000"
          admin_url: "http://10.0.2.15:35357"
    - role: openstack-rally
      rally_dir: /home/tester/rally
