
- name: install MySQL-python
  pip: name=MySQL-python virtualenv={{ keystone_dir }}/venv

- name: Install dependencies
  apt: name={{ item }} update_cache=yes
  with_items: 
    - python-psycopg2
    - libpq-dev
  sudo: yes

- name: install psycopg2
  pip: name=psycopg2 virtualenv={{ keystone_dir }}/venv
