- name: Configure Keystone database
  ini_file: >
    dest=/etc/keystone/keystone.conf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items:
    - section: database
      option: connection
      value: "{{ global_db }}://keystone:{{ global_keystone_password }}@{{ hostvars[groups[cluster_name + '_master'][0]].openstack.private_v4 }}/keystone"
  become: yes
- name: Configure Keystone database2
  ini_file: >
    dest=/etc/keystone/keystone.conf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items:
    - section: DEFAULT
      option: verbose
      value: "false"
  become: yes
- name: Sync Keystone database
  command: '/bin/sh -c "{{ keystone_dir }}/venv/bin/keystone-manage db_sync" keystone'
  ignore_errors: yes
  when: inventory_hostname == groups[cluster_name + '-slave-1'][0]

- debug: msg="{{inventory_hostname}}, {{hostvars[inventory_hostname].openstack.private_v4}}"

- include: run_uwsgi.yml

- pause: seconds=2

- include: endpoints.yml
  when: inventory_hostname == groups[cluster_name + '-slave-1'][0]
- include: tenants.yml
  when: inventory_hostname == groups[cluster_name + '-slave-1'][0]
- include: users.yml
  when: inventory_hostname == groups[cluster_name + '-slave-1'][0]
- include: roles.yml
  when: inventory_hostname == groups[cluster_name + '-slave-1'][0]
