- name: Configure Keystone database
  ini_file: >
    dest=/etc/keystone/keystone.conf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items:
    - section: database
      option: connection
      value: "{{ global_db }}://keystone:{{ global_keystone_password }}@localhost/keystone"
  become: yes


- name: Configure Keystone database2
  ini_file: >
    dest=/etc/keystone/keystone.conf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items:
    - section: DEFAULT
      option: verbose
      value: "false"
  become: yes
- name: Configure token
  ini_file: >
    dest=/etc/keystone/keystone.conf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items:
    - section: token
      option: provider
      value: "{{ global_token_provider }}"
  become: yes
- name: Configure fernet tokens directory
  ini_file: >
    dest=/etc/keystone/keystone.conf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items:
    - section: fernet_tokens
      option: key_repository
      value: "/etc/keystone/fernet-keys/"
  when: global_token_provider == "fernet"
  become: yes
- name: Create fernet tokens
  shell: "{{ keystone_dir }}/venv/bin/keystone-manage fernet_setup"
  #ignore_errors: yes
  when: global_token_provider == "fernet"
  become: "modis"
- name: pause
  pause: seconds=7

- name: Sync Keystone database
  command: '/bin/sh -c "{{ keystone_dir }}/venv/bin/keystone-manage db_sync" keystone'
  ignore_errors: yes
  become: modis
  #when: inventory_hostname == groups[cluster_name + '-slave-1'][0]

#- debug: msg="{{inventory_hostname}}, {{hostvars[inventory_hostname].openstack.private_v4}}"

- include: run_uwsgi.yml

- pause: seconds=5

- include: endpoints.yml
  #when: inventory_hostname == groups[cluster_name + '-slave-1'][0]
- include: tenants.yml
  #when: inventory_hostname == groups[cluster_name + '-slave-1'][0]
- include: users.yml
  #when: inventory_hostname == groups[cluster_name + '-slave-1'][0]
- include: roles.yml
  #when: inventory_hostname == groups[cluster_name + '-slave-1'][0]
