- name: copy nginx config
  template: src=roles/openstack-keystone/templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: yes

- name: Create server blocks
  template: src=roles/openstack-keystone/templates/keystone_server_block.j2 dest=/etc/nginx/sites-available/keystone
  sudo: yes

- name: check keystone slink is present
  stat: path=/etc/nginx/sites-enabled/keystone
  register: link_is_ok

- shell: "ln -s /etc/nginx/sites-available/keystone /etc/nginx/sites-enabled"
  sudo: yes
  when: link_is_ok.stat.exists == False

- name: copy uwsgi ini file
  template: src=roles/openstack-keystone/templates/uwsgi-keystone.ini.j2 dest=/tmp/uwsgi-keystone-{{ item.endpoint_role }}.ini owner={{ global_os_user }}
  with_items:
    - { endpoint_role: 'admin' }
    - { endpoint_role: 'main' }
  sudo: yes

- name: Restart nginx
  service: name=nginx state=restarted
  sudo: yes

- name: Running Keystone over uWSGI #only admin supported so far
  shell: "source {{ keystone_dir }}/venv/bin/activate; {{ keystone_dir }}/venv/bin/uwsgi --daemonize2 --ini /tmp/uwsgi-keystone-{{ item }}.ini"
  with_items:
    - 'admin'
    - 'main'


