- name: Stop nginx
  service: name=nginx state=stopped

- name: Stop apache2
  service: name=apache2 state=stopped

- name: Stop uwsgi
  shell: "kill -HUP `pidof uwsgi` &> /dev/null"
  sudo: yes
  ignore_errors: yes

- name: PostgreSQL | delete cluster
  shell: pg_dropcluster --stop {{postgresql_version}} {{postgresql_cluster_name}}
  sudo: yes
  ignore_errors: yes

- name: stop mariadb
  service: name=mysql state=stopped
  sudo: yes
  ignore_errors: yes

- shell: "killall mysqld"
  ignore_errors: yes

- name: Stop postgresql
  service: name=postgresql state=stopped
  sudo: yes
  #when: global_db == "postgresql"

- mount: name="{{mariadb_datadir}}" src={{global_fs_src}} fstype={{global_fs_type}} state=unmounted
  sudo: yes

- mount: name="/var/lib/postgresql" src={{global_fs_src}} fstype={{global_fs_type}} state=unmounted
  sudo: yes
