---

- name: installing MariaDB packages
  apt: name={{ item }} state=present #update_cache=yes
  with_items:
    - "{{mariadb_package_client}}"
    - "{{mariadb_package_server}}"
    - python-mysqldb
  notify: stop mariadb

- name: installing MariaDB tools
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mysqltuner
    - percona-toolkit
  when: mariadb_install_tools
  tags: [mysql-tools]
