---

#- name: Download Cassandra checksum
#  local_action: get_url url={{ cassandra_checksum_url }} dest=files/
#  become: False


#- name: Extract Cassandra checksum
#  set_fact: cassandra_md5="{{ lookup('file', cassandra_checksum) }}"
- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Download Cassandra tarball
  get_url: url=http://www-us.apache.org/dist/cassandra/3.11.2/apache-cassandra-3.11.2-bin.tar.gz dest=/opt/ #checksum="md5:{{ cassandra_md5 }}"
#  #when: "'{{ inventory_hostname }}' == '{{ active_master_inventory_hostname }}'"


#- name: distribute Cassandra tarball
#  synchronize:
#    src: "/opt/{{ cassandra_file }}"
#    dest: "/opt/{{ cassandra_file }}"
#  delegate_to: "{{ active_master_inventory_hostname }}"

- name: unpack Cassandra
  unarchive: copy=no src=/opt/{{ cassandra_file }} dest=/opt

- name: symlink Cassandra
  file: src={{ cassandra_home }} dest=/opt/cassandra state=link

- name: JVM.OPTIONS
  copy:
    src: jvm.options.j2
    dest: /opt/cassandra/conf/jvm.options
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

#- name: Install libjna-java
#  become: yes
#  apt: name=libjna-java state=latest

#- name: Install libjemalloc1
#  become: yes
#  apt: name=libjemalloc1 state=latest

#- name: symlink Cassandra
#  shell: ln -s /usr/share/java/jna.jar /opt/cassandra/lib
#  ignore_errors: yes
