---

- hosts: "{{ cluster_name }}_slaves"
  roles:
    - role: install_uwsgi
      keystone_dir: /home/{{ global_os_user }}/keystone
      keystone_database_url: "{{ global_db }}://keystone:{{ global_keystone_password }}@{{hostvars[inventory_hostname]['groups']['my_name_keystone-master'][0]}}/keystone"
      keystone_admin_token: "{{ global_keystone_token }}"
      keystone_admin_port: 35357
      keystone_port: 5000
      keystone_tenants:
        - name: admin
          description: "Admin tenant"
        - name: service
          description: "Service tenant"
        - name: demo
          description: "Demo tenant"
      keystone_users:
        - name: "{{ global_keystone_user }}"
          password: "{{ global_keystone_password }}"
          tenant: admin
        - name: demo
          password: "{{ global_keystone_password }}"
          tenant: demo
      keystone_roles:
        - name: admin
          user: admin
          tenant: admin
        - name: demo
          user: demo
          tenant: demo
      keystone_services:
        - name: keystone
          service_type: identity
      keystone_endpoints:
        - service_name: keystone
          public_url: "http://127.0.0.1:5000"
          internal_url: "http://127.0.0.1:5000"
          admin_url: "http://127.0.0.1:35357"
