---

- hosts: all

  pre_tasks:
    - apt: update_cache=yes
      sudo: yes
    - apt: name=git state=present
      sudo: yes
    #- apt: name=python-dev state=present
    #  sudo: yes

    #- name: Install scipy Deps
    #  apt: name={{ item }} state=build-dep
    #  with_items: list_of_packages
    - name: Install scipy Packages
      apt: name={{ item }} state=present
      with_items: list_of_packages

  vars:
      global_db: ""
      list_of_packages:
          - python-numpy
          - python-scipy
          - python-matplotlib
  roles:
    - role: postgresql  
      install_flag: "yes"


      postgresql_admin_user: "postgres"

    - role: ansible-mariadb
      install_flag: "yes"
      mariadb_root_username: "{{ global_mariadb_user }}"
      mariadb_root_password: "{{ global_mariadb_password }}"
      mariad_default_config:
        - name: 'mysqld'
          config:
            - innodb_lof_file_size = 48M
      sudo: yes

    - role: openstack-keystone
      install_flag: "yes"
      keystone_dir: /home/{{ global_os_user }}/keystone
      keystone_database_url: "{{ global_db }}://keystone:{{ global_keystone_password }}@localhost/keystone"
      keystone_admin_token: "{{ global_keystone_token }}"
      keystone_admin_port: 35357
      keystone_port: 5000
      keystone_tenants:
        - name: admin
          description: "Admin tenant"
        - name: service
          description: "Service tenant"
        - name: demo
          description: "Demo tenant"
      keystone_users:
        - name: "{{ global_keystone_user }}"
          password: "{{ global_keystone_password }}"
          tenant: admin
        - name: demo
          password: "{{ global_keystone_password }}"
          tenant: demo
      keystone_roles:
        - name: admin
          user: admin
          tenant: admin
        - name: demo
          user: demo
          tenant: demo
      keystone_services:
        - name: keystone
          service_type: identity
      keystone_endpoints:
        - service_name: keystone
          public_url: "http://127.0.0.1:5000"
          internal_url: "http://127.0.0.1:5000"
          admin_url: "http://127.0.0.1:35357"

    - role: openstack-rally
      rally_dir: /home/{{ global_os_user }}/rally


