---

- hosts: "{{ cluster_name }}-master"

  pre_tasks:
    - mount: name={{mariadb_datadir}} src={{hardware_src}} fstype={{hardware_type}} state=mounted
      ignore_errors: yes
      become: yes

    - shell: "rm -rf {{mariadb_datadir}}/*"
      become: yes
      ignore_errors: yes
    - command: chown mysql:mysql {{mariadb_datadir}} -R
      become: yes
      ignore_errors: yes
  vars:
      mariadb_datadir: /var/lib/mysql



