---

- hosts: "{{ cluster_name }}-master"

  pre_tasks:
    - mount: name="/var/lib/postgresql/" src={{hardware_src}} fstype={{hardware_type}} state=mounted
      sudo: yes
      ignore_errors: yes

    - shell: "rm -rf /var/lib/postgresql/*"
      sudo: yes
      ignore_errors: yes
    - shell: "rm -rf /var/log/mysql/*"
      sudo: yes
      ignore_errors: yes
