---

- hosts: "my_name_keystone-master"

  pre_tasks:
    - mount: name="/var/lib/postgresql/" src={{hardware_src}} fstype={{hardware_type}} state=mounted
      sudo: yes
      ignore_errors: yes

    - shell: "rm -rf /var/lib/postgresql/*"
      sudo: yes
      ignore_errors: yes
    - shell: "rm -rf /var/log/postgresql/*"
      sudo: yes
      ignore_errors: yes
