---

- hosts: "{{ cluster_name }}_slaves"
  pre_tasks:
    - name: Install Apache2
      apt: name={{ item }} state=present update_cache=yes
      with_items:
          - apache2
          - libapache2-mod-wsgi
      become: yes
    - name: Remove default config
      shell: "rm -rf /etc/apache2/sites-enabled/*"
      become: yes
      ignore_errors: yes
    - name: Remove default config
      shell: "rm -rf /etc/apache2/sites-available/*"
      become: yes
      ignore_errors: yes
  roles:
    - role: run_apache_keystone
      keystone_dir: /home/{{ global_os_user }}/keystone
      keystone_database_url: "{{ global_db }}://keystone:{{ global_keystone_password }}@{{hostvars[groups[cluster_name + '_master'][0]].openstack.private_v4}}/keystone"
      keystone_admin_token: "{{ global_keystone_token }}"
      keystone_admin_port: 35357
      keystone_port: 5000
      keystone_tenants:
        - name: admin
          description: "Admin tenant"
        - name: service
          description: "Service tenant"
        - name: demo
          description: "Demo tenant"
      keystone_users:
        - name: "{{ global_keystone_user }}"
          password: "{{ global_keystone_password }}"
          tenant: admin
        - name: demo
          password: "{{ global_keystone_password }}"
          tenant: demo
      keystone_roles:
        - name: admin
          user: admin
          tenant: admin
        - name: demo
          user: demo
          tenant: demo
      keystone_services:
        - name: keystone
          service_type: identity
      keystone_endpoints:
        - service_name: keystone
          public_url: "http://127.0.0.1:5000"
          internal_url: "http://127.0.0.1:5000"
          admin_url: "http://127.0.0.1:35357"
