---
- hosts: "my_name-cassandra-master:my_name-cassandra-slaves"
  pre_tasks:

    #- name: waiting for cassandra to stop
    #  pause: seconds=6

    - name: kill cassandra
      shell: "kill -9 `pidof java` &> /dev/null"
      sudo: yes
      ignore_errors: yes
    - name: del /opt/cassandra/data
      file: path=/opt/cassandra/data state=absent
      sudo: yes
      ignore_errors: yes


    #- name: del database logs
    #  file: path=/var/log/cassandra state=absent
    #  sudo: yes
    #  ignore_errors: yes

    #- name: del logs
    #  file: path=/var/log/cassandra state=directory
    #  sudo: yes
    - name: del cassandra.log
      file: path=/home/{{ ansible_user }}/cassandra.log state=absent
      become: true
      ignore_errors: yes
    - file:
        path: /opt/cassandra/data
        state: directory
        mode: 0755
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    #- shell: killall java
    #  sudo: yes
    #  ignore_errors: yes

    #- name: waiting for cassandra to stop
    #  pause: seconds=5
