---

- hosts: "my_name_keystone-master"

  pre_tasks:
    - name: Stop postgresql
      service: name=postgresql state=stopped
      sudo: yes
    - name: PostgreSQL | delete cluster
      shell: pg_dropcluster --stop {{postgresql_version}} {{postgresql_cluster_name}}
      sudo: yes
      ignore_errors: yes
    - name: Stop postgresql
      service: name=postgresql state=stopped
      sudo: yes
  vars:
    postgresql_version: 10
    postgresql_cluster_name: "main"
