---

- hosts: all

  pre_tasks:
    - name: stop mariadb
      service: name=mysql state=stopped
      become: yes
      ignore_errors: yes
    - shell: killall mysqld
      become: yes
      ignore_errors: yes
