# file: postgresql/tasks/users.yml


- name: PostgreSQL | Restart PostgreSQL
  service:
    name: "postgresql"
    state: restarted

- name: PostgreSQL | Create users
  postgresql_user:
    name: keystone
    password: "{{ global_keystone_password }}"
    port: "{{postgresql_port}}"
    state: present
    login_user: "{{postgresql_admin_user}}"
    login_password: "{{ global_postgresql_password }}"

