---

  

- name: Ensures {{project_root}}/conf dir exists
  file: path=/etc/tarantool/instances.enabled/db_init state=directory
  sudo: yes


- name: Ensures {{project_root}}/conf dir exists
  file: path=/etc/tarantool/instances.enabled/db_folder state=directory
  sudo: yes

- name: Copy the shard1_db.lua file
  template:
    src: templates/shard1_db.lua
    dest: /etc/tarantool/instances.enabled/db_folder/shard1_db.lua
  sudo: yes
  ignore_errors: yes
  
  
- name: Ensures {{project_root}}/conf dir exists
  file: path=/etc/tarantool/instances.enabled/keystone_1 state=directory
  sudo: yes

- name: Ensures {{project_root}}/conf dir exists
  file: path=/etc/tarantool/instances.enabled/keystone_2 state=directory
  sudo: yes

  
- name: Copy the shard_keystone.lua file
  template:
    src: templates/shard_keystone_1.lua
    dest: /etc/tarantool/instances.enabled/keystone_1/shard_keystone_1.lua
  sudo: yes
  ignore_errors: yes
- name: Copy the shard_keystone.lua file
  template:
    src: templates/shard_keystone_2.lua
    dest: /etc/tarantool/instances.enabled/keystone_2/shard_keystone_2.lua
  sudo: yes
  ignore_errors: yes
  

- name: Copy the db_init.lua file
  template:
    src: templates/init_db.lua
    dest: /etc/tarantool/instances.enabled/db_init/init_db.lua
  sudo: yes
  ignore_errors: yes


- name: copy uuid4 lua script
  copy: src=files/uuid4.lua dest="/etc/tarantool/instances.enabled/keystone_1/uuid4.lua" owner={{global_os_user}} group={{global_os_user}} mode=0751
  sudo: yes

- name: copy sha512 lua script
  copy: src=files/sha512.lua dest="/etc/tarantool/instances.enabled/keystone_1/sha512.lua" owner={{global_os_user}} group={{global_os_user}} mode=0751
  sudo: yes
  
- name: copy uuid4 lua script
  copy: src=files/uuid4.lua dest="/etc/tarantool/instances.enabled/keystone_2/uuid4.lua" owner={{global_os_user}} group={{global_os_user}} mode=0751
  sudo: yes

- name: copy sha512 lua script
  copy: src=files/sha512.lua dest="/etc/tarantool/instances.enabled/keystone_2/sha512.lua" owner={{global_os_user}} group={{global_os_user}} mode=0751
  sudo: yes


- name: copy uuid4 lua script
  copy: src=files/uuid4.lua dest="/etc/tarantool/instances.enabled/db_folder/uuid4.lua" owner={{global_os_user}} group={{global_os_user}} mode=0751
  sudo: yes

- name: copy sha512 lua script
  copy: src=files/sha512.lua dest="/etc/tarantool/instances.enabled/db_folder/sha512.lua" owner={{global_os_user}} group={{global_os_user}} mode=0751
  sudo: yes

- name: copy uuid4 lua script
  copy: src=files/uuid4.lua dest="/etc/tarantool/instances.enabled/db_init/uuid4.lua" owner={{global_os_user}} group={{global_os_user}} mode=0751
  sudo: yes

- name: copy sha512 lua script
  copy: src=files/sha512.lua dest="/etc/tarantool/instances.enabled/db_init/sha512.lua" owner={{global_os_user}} group={{global_os_user}} mode=0751
  sudo: yes


- name: delete example
  shell: rm /etc/tarantool/instances.enabled/example.lua
  sudo: yes
  ignore_errors: yes

- name: Stop tarantool
  shell: killall tarantool
  sudo: yes
  ignore_errors: yes

