# file: postgresql/tasks/main.yml

- include: install.yml
  tags: [postgresql, postgresql-install]
  when: install_flag == "yes"
- include: extensions.yml
  when: install_flag == "yes" and global_db == 'postgresql'
- include: second.yml
  when: install_flag == "no" and global_db == 'postgresql'


