- include: configure.yml
  tags: [postgresql, postgresql-configure]

- include: users.yml
  tags: [postgresql, postgresql-users]

- include: databases.yml
  tags: [postgresql, postgresql-databases]

#- include: users_privileges.yml
#  tags: [postgresql, postgresql-users]

#- include: monit.yml
#  when: monit_protection is defined and monit_protection == true
#  tags: [postgresql, postgresql-monit]
